### ISSUE TITLE
Notice: Trying to access array offset on value of type null in auto_entitylabel_settings_form()

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/auto_entitylabel#10]
This notice is thrown when creating a new content type:
1. Create a new content type
2. Visit `admin/structure/types/manage/YOUR_TYPE/auto_label`

The problem is that `$config` is empty for new types. PHP 7.4+ throw a notice when trying to access an array value in an empty variable. 

Solution: use an inline if statement as in:

`'#default_value' => !empty($config['status']) ? $config['status'] : '',`

**Comment by herbdool** [comment]
Fixed in current release.
