### ISSUE TITLE
Anything preventing a release?

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/auto_entitylabel#2]
@BWPanda looks like you ported. Is there anything stopping a release?

**Comment by ghost** [comment]
Thanks for the nudge @herbdool! I barely even remember doing this. Must have been one of my first ports as the README file isn't listing maintainers or anything...

In looking over the code, I've noticed a few things that could use cleaning up/simplifying. Also, this port happened a while ago and new features/bug fixes have been added to the Drupal module in the meantime. So I'll need to go through and make sure all is up-to-date.

Will work on this and post a (possibly pre-release) version soon.

**Comment by herbdool** [comment]
I wonder if removing the ability to use PHP should be done first. The latest version has a hook so someone could use that instead. The general approach in Backdrop has been to remove ability to insert PHP via the UI.

**Comment by ghost** [comment]
I needed this on a site I'm building, so decided just to create a beta release: https://github.com/backdrop-contrib/auto_entitylabel/releases/tag/1.x-1.0.0-beta1

Hopefully with a release more people can use it, which might mean more help fixing bugs and getting this to v1.0.0.
