### ISSUE TITLE
Bring up-to-date with Drupal module

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/auto_entitylabel#4]
The Drupal module has had quite a few commits since this was ported, so we need to bring this module up-to-date.

**Comment by herbdool** [comment]
@BWPanda I've created a PR. It's not fully working for me. Not sure if it was working before.

For a project I actually used `auto_nodetitle` but I had to fork it to update it from d7. If this module gets working I could switch to this one. It has a similar hook.

**Comment by ghost** [comment]
Thanks @herbdool. It looks like more work is needed to get this working and Backdrop-compatible... Are you interested in co-maintaining this module?

I actually started my own update before I saw your PR. I cloned the latest D7 code and started a new migration from scratch (making major changes along the way to simplify things, remove what I think is unnecessary, etc.). Maybe my work could become a 2.x branch...

**Comment by herbdool** [comment]
I'm not sure if I'll be using it or not so not sure about maintaining. I'll think about it.

I would caution against a 2.x branch unless you're making big API breaking changes.

**Comment by herbdool** [comment]
@BWPanda I'll take you up on co-maintaining this module. I'll create a PR to add my name.
