### ISSUE TITLE
Undefined function `entity_save()` in `auto_entitylabel_entity_update_action()`

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/auto_entitylabel#9]
Once #8 is fixed, line 351 of `auto_entitylabel.module` needs to be fixed as well. That line invokes `entity_save()`, which does not exist in Backdrop. Instead use `$entity->save()`

**Comment by herbdool** [comment]
Fixed as part of https://github.com/herbdool/auto_entitylabel/commit/9e9572377c905f9d2a750f17c776fc209ecb33cf
